version: '3.8'

services:
  frontend:
    build:
      context: ./fibonacci-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:3001}
    volumes:
      - ./fibonacci-app/src:/app/src
      - ./fibonacci-app/public:/app/public
    depends_on:
      - backend

  backend:
    build:
      context: ./fibonacci-server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=${BACKEND_PORT:-3001}
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./fibonacci-server/src:/app/src
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:alpine

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

networks:
  default:
    name: fibonacci-network
